import { compile } from 'json-schema-to-typescript';
import fs from 'node:fs';
import path from 'node:path';

async function check() {
  const schemaPath = path.resolve('src/data-format/nfcweb-tag-registry.schema.json');
  const outputPath = path.resolve('src/data-format/generated/nfcweb-tag-registry.ts');

  if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found at ${schemaPath}`);
    process.exit(1);
  }

  if (!fs.existsSync(outputPath)) {
    console.error(`Generated artifact not found at ${outputPath}. Run 'npm run generate:data-format'.`);
    process.exit(1);
  }

  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

  const bannerComment = `/* eslint-disable */
/**
 * DO NOT EDIT DIRECTLY.
 * This file is automatically generated from src/data-format/nfcweb-tag-registry.schema.json.
 * Run 'npm run generate:data-format' to regenerate after schema edits.
 */
`;

  const expectedTs = await compile(schema, 'NfcwebTagRegistryExportV1', {
    bannerComment,
    style: {
      singleQuote: true,
      semi: true
    },
    unreachableDefinitions: true
  });

  const actualTs = fs.readFileSync(outputPath, 'utf8');

  // Normalize line endings for reliable comparison across platforms
  const normExpected = expectedTs.replace(/\r\n/g, '\n').trim();
  const normActual = actualTs.replace(/\r\n/g, '\n').trim();

  if (normExpected !== normActual) {
    console.error(`DRIFT DETECTED: ${outputPath} is out of sync with ${schemaPath}.`);
    console.error(`Please run 'npm run generate:data-format' to synchronize the generated types.`);
    process.exit(1);
  }

  console.log(`PASS: Generated TypeScript types are strictly in sync with canonical JSON schema.`);
}

check().catch((err) => {
  console.error('Check failed with error:', err);
  process.exit(1);
});
