import { compile } from 'json-schema-to-typescript';
import fs from 'node:fs';
import path from 'node:path';

const SCHEMA_DIR = path.resolve('src/data-format/schemas');
const GENERATED_DIR = path.resolve('src/data-format/generated');
const BUNDLES_DIR = path.resolve('src/data-format/generated/bundles');
const OUTPUT_TS_PATH = path.resolve('src/data-format/generated/nfcweb-tag-registry.ts');

export function loadCanonicalSchemas() {
  const ndefPath = path.join(SCHEMA_DIR, 'ndef-record.schema.json');
  const tagPath = path.join(SCHEMA_DIR, 'nfc-tag.schema.json');
  const registryPath = path.join(SCHEMA_DIR, 'nfc-tag-registry.schema.json');

  if (!fs.existsSync(ndefPath) || !fs.existsSync(tagPath) || !fs.existsSync(registryPath)) {
    throw new Error('One or more canonical schema files are missing in src/data-format/schemas');
  }

  const ndefSchema = JSON.parse(fs.readFileSync(ndefPath, 'utf8'));
  const tagSchema = JSON.parse(fs.readFileSync(tagPath, 'utf8'));
  const registrySchema = JSON.parse(fs.readFileSync(registryPath, 'utf8'));

  return { ndefSchema, tagSchema, registrySchema };
}

export function buildNfcTagBundle(tagSchema: any, ndefSchema: any) {
  return {
    ...tagSchema,
    $defs: {
      'ndef-record': ndefSchema
    }
  };
}

export function buildNfcTagRegistryBundle(registrySchema: any, tagSchema: any, ndefSchema: any) {
  return {
    ...registrySchema,
    $defs: {
      'nfc-tag': tagSchema,
      'ndef-record': ndefSchema
    }
  };
}

export async function generateTypeScriptCode(registrySchema: any, tagSchema: any, ndefSchema: any): Promise<string> {
  // Map anchor references for json-schema-to-typescript parser
  const preparedNdefSchema = JSON.parse(JSON.stringify(ndefSchema));
  if (Array.isArray(preparedNdefSchema.oneOf)) {
    preparedNdefSchema.oneOf = preparedNdefSchema.oneOf.map((item: any) => {
      if (item.$ref === '#text') return { $ref: '#/$defs/TextRecord' };
      if (item.$ref === '#url') return { $ref: '#/$defs/UrlRecord' };
      if (item.$ref === '#mime') return { $ref: '#/$defs/MimeRecord' };
      if (item.$ref === '#empty') return { $ref: '#/$defs/EmptyRecord' };
      return item;
    });
  }

  const customResolver = {
    order: 1,
    canRead: (file: any) => file.url.startsWith('https://nfcweb.ai.studio/'),
    read: (file: any) => {
      if (file.url === 'https://nfcweb.ai.studio/schemas/ndef-record/v1') {
        return JSON.stringify(preparedNdefSchema);
      }
      if (file.url === 'https://nfcweb.ai.studio/schemas/nfc-tag/v1') {
        return JSON.stringify(tagSchema);
      }
      throw new Error(`Unresolved schema reference: ${file.url}`);
    }
  };

  const bannerComment = `/* eslint-disable */
/**
 * DO NOT EDIT DIRECTLY.
 * This file is automatically generated from canonical schemas:
 *   - src/data-format/schemas/ndef-record.schema.json
 *   - src/data-format/schemas/nfc-tag.schema.json
 *   - src/data-format/schemas/nfc-tag-registry.schema.json
 * Run 'npm run generate:data-format' to regenerate after schema edits.
 */
`;

  const compiled = await compile(registrySchema, 'NfcTagRegistryV1', {
    bannerComment,
    style: {
      singleQuote: true,
      semi: true
    },
    $refOptions: {
      resolve: {
        nfcweb: customResolver as any
      }
    }
  });

  const compatibilityAliases = `
// Domain compatibility aliases for backwards compatibility
export type ExportableTagV1 = NfcTagV1;
export type NFCWebTagRegistryInterchangeSchema = NfcTagRegistryV1;
export type NfcwebTagRegistryExportV1 = NfcTagRegistryV1;
export type TagRegistryExportDocumentV1 = NfcTagRegistryV1;

export type NdefRecord = NdefRecordV1;
export type TextRecord = TextRecordV1;
export type UrlRecord = UrlRecordV1;
export type MimeRecord = MimeRecordV1;
export type EmptyRecord = EmptyRecordV1;
`;

  return compiled + compatibilityAliases;
}

async function main() {
  const { ndefSchema, tagSchema, registrySchema } = loadCanonicalSchemas();

  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.mkdirSync(BUNDLES_DIR, { recursive: true });

  // 1. Generate Bundles
  const tagBundle = buildNfcTagBundle(tagSchema, ndefSchema);
  const tagBundlePath = path.join(BUNDLES_DIR, 'nfc-tag.bundle.json');
  fs.writeFileSync(tagBundlePath, JSON.stringify(tagBundle, null, 2) + '\n', 'utf8');

  const registryBundle = buildNfcTagRegistryBundle(registrySchema, tagSchema, ndefSchema);
  const registryBundlePath = path.join(BUNDLES_DIR, 'nfc-tag-registry.bundle.json');
  fs.writeFileSync(registryBundlePath, JSON.stringify(registryBundle, null, 2) + '\n', 'utf8');

  console.log(`Generated bundles successfully at ${BUNDLES_DIR}`);

  // 2. Generate TypeScript definitions
  const tsContent = await generateTypeScriptCode(registrySchema, tagSchema, ndefSchema);
  fs.writeFileSync(OUTPUT_TS_PATH, tsContent, 'utf8');
  console.log(`Generated TypeScript types successfully at ${OUTPUT_TS_PATH}`);
}

if (process.argv[1] && process.argv[1].includes('generate-data-format')) {
  main().catch((err) => {
    console.error('Failed to generate schemas and TypeScript types:', err);
    process.exit(1);
  });
}
