import { compile } from 'json-schema-to-typescript';
import fs from 'node:fs';
import path from 'node:path';

async function generate() {
  const schemaPath = path.resolve('src/data-format/nfcweb-tag-registry.schema.json');
  const outputPath = path.resolve('src/data-format/generated/nfcweb-tag-registry.ts');

  if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found at ${schemaPath}`);
    process.exit(1);
  }

  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

  const bannerComment = `/* eslint-disable */
/**
 * DO NOT EDIT DIRECTLY.
 * This file is automatically generated from src/data-format/nfcweb-tag-registry.schema.json.
 * Run the 'generate:data-format' package script to regenerate after schema edits.
 */
`;

  const ts = await compile(schema, 'NfcwebTagRegistryExportV1', {
    bannerComment,
    style: {
      singleQuote: true,
      semi: true
    },
    unreachableDefinitions: true
  });

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, ts, 'utf8');
  console.log(`Generated TypeScript types successfully at ${outputPath}`);
}

generate().catch((err) => {
  console.error('Failed to generate TypeScript types from schema:', err);
  process.exit(1);
});
